networks:
  app:
    driver: bridge

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app:app --host 0.0.0.0 --workers 2"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - database
      - redis-cache
    ports:
      - "8000:8000"
    networks:
      - app

  database:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app

  redis-cache:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_DB_PASSWORD=${REDIS_DB_PASSWORD}
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_DB_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default off nopass nocommands" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USERNAME on >$REDIS_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    restart: unless-stopped
    networks:
      - app

volumes:
  postgres_data:
  redis_data:
